import { type Festival, type InsertFestival } from "../shared/schema";

interface CalendarEvent {
  date: string;
  title: string;
  type: 'festival' | 'appearance' | 'disappearance' | 'ekadasi' | 'fast' | 'celebration';
  isFasting: boolean;
  description?: string;
  fastingInstructions?: string;
}

export function parseVaishnavCalendar(calendarText: string): CalendarEvent[] {
  const events: CalendarEvent[] = [];
  const lines = calendarText.split('\n');
  
  let currentDate = '';
  let currentYear = '';
  
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    
    // Skip empty lines, headers, and separators
    if (!line || line.startsWith('---') || line.includes('Masa, Gaurabda') || 
        line.includes('Seattle [United States') || line.includes('DATE') ||
        line.includes('Notes:') || line.includes('DST -') || line.includes('LT -') ||
        line.includes('Generated by')) {
      continue;
    }
    
    // Check if line contains a date
    const dateMatch = line.match(/(\d{1,2}\s+\w{3}\s+\d{4})\s+\w{2}/);
    if (dateMatch) {
      currentDate = dateMatch[1];
      const year = currentDate.split(' ')[2];
      if (year) currentYear = year;
      
      // Extract events from the same line after the date
      const afterDate = line.substring(line.indexOf(dateMatch[0]) + dateMatch[0].length);
      const eventText = afterDate.replace(/^\s+\w+\s+\w+\s+\w+\s*\*?\s*/, '').trim();
      
      if (eventText) {
        processEventText(eventText, currentDate, events);
      }
    } else if (currentDate && line.includes('--')) {
      // This is an event line continuation
      processEventText(line, currentDate, events);
    } else if (currentDate && (line.includes('Fasting for') || line.includes('Break fast') || 
               line.includes('Fast today') || line.includes('Ekadasi'))) {
      // Fasting instructions
      processEventText(line, currentDate, events);
    } else if (currentDate && line.match(/^\s+[A-Z]/)) {
      // Other events (starting with capital letter, indented)
      processEventText(line, currentDate, events);
    }
  }
  
  return events;
}

function processEventText(eventText: string, date: string, events: CalendarEvent[]): void {
  eventText = eventText.trim();
  
  if (!eventText || eventText.length < 3) return;
  
  // Parse different types of events
  if (eventText.includes('-- Appearance')) {
    const name = eventText.replace('-- Appearance', '').trim();
    events.push({
      date: parseDate(date),
      title: `${name} - Appearance`,
      type: 'appearance',
      isFasting: eventText.includes('Fast today'),
      description: `Appearance day of ${name}`
    });
  } else if (eventText.includes('-- Disappearance')) {
    const name = eventText.replace('-- Disappearance', '').trim();
    events.push({
      date: parseDate(date),
      title: `${name} - Disappearance`,
      type: 'disappearance',
      isFasting: eventText.includes('Fast today'),
      description: `Disappearance day of ${name}`
    });
  } else if (eventText.includes('Fasting for')) {
    const ekadasi = eventText.replace('Fasting for', '').trim();
    events.push({
      date: parseDate(date),
      title: ekadasi,
      type: 'ekadasi',
      isFasting: true,
      description: `Ekadasi fasting day`,
      fastingInstructions: eventText
    });
  } else if (eventText.includes('Break fast')) {
    // Add breaking fast instruction to existing ekadasi event
    const existing = events.find(e => e.date === parseDate(date) && e.type === 'ekadasi');
    if (existing) {
      existing.fastingInstructions += `\n${eventText}`;
    }
  } else if (eventText.includes('Fast today')) {
    const title = eventText.replace('(Fast today)', '').trim();
    events.push({
      date: parseDate(date),
      title: title || 'Fasting Day',
      type: 'fast',
      isFasting: true,
      description: 'Fasting observance'
    });
  } else if (eventText.includes('Yatra') || eventText.includes('Utsava') || 
             eventText.includes('Purnima') || eventText.includes('Ratri') ||
             eventText.includes('Sankranti') || eventText.includes('Pancami')) {
    events.push({
      date: parseDate(date),
      title: eventText,
      type: 'festival',
      isFasting: eventText.includes('Fast today'),
      description: 'Sacred festival celebration'
    });
  } else if (eventText.length > 5) {
    // Generic spiritual event
    events.push({
      date: parseDate(date),
      title: eventText,
      type: 'celebration',
      isFasting: eventText.includes('Fast today'),
      description: 'Spiritual observance'
    });
  }
}

function parseDate(dateString: string): string {
  try {
    // Convert "1 Jan 2025" to "2025-01-01"
    const parts = dateString.trim().split(' ');
    if (parts.length >= 3) {
      const day = parts[0].padStart(2, '0');
      const month = getMonthNumber(parts[1]);
      const year = parts[2];
      return `${year}-${month}-${day}`;
    }
  } catch (error) {
    console.error('Error parsing date:', dateString, error);
  }
  return dateString; // fallback
}

function getMonthNumber(monthName: string): string {
  const months: { [key: string]: string } = {
    'Jan': '01', 'Feb': '02', 'Mar': '03', 'Apr': '04',
    'May': '05', 'Jun': '06', 'Jul': '07', 'Aug': '08',
    'Sep': '09', 'Oct': '10', 'Nov': '11', 'Dec': '12'
  };
  return months[monthName] || '01';
}

export function convertToFestivals(events: CalendarEvent[]): InsertFestival[] {
  return events.map(event => ({
    name: event.title,
    date: event.date,
    description: event.description || '',
    significance: event.isFasting ? 'Fasting day' : 'Celebration',
    observances: event.fastingInstructions ? [event.fastingInstructions] : null
  }));
}